In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [7]:
b = np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
c = b.reshape(2,4,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [10]:
x = np.zeros(5,dtype=np.int)
print(x)

[0 0 0 0 0]


In [15]:
y = np.linspace(10,20,5,endpoint=False)
y

array([10., 12., 14., 16., 18.])

In [17]:
z = np.logspace(1.0,3.0,num=10,base=2)
z

array([2.        , 2.33305808, 2.72158   , 3.1748021 , 3.70349885,
       4.32023896, 5.0396842 , 5.87893797, 6.85795186, 8.        ])

In [18]:
r = np.arange(10)
print(r)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
s = slice(1,8,2)
print(r[s])

[1 3 5 7]


In [20]:
print(r[1:8:2])

[1 3 5 7]


In [21]:
t = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(t[1:])

[[4 5 6]
 [7 8 9]]


In [34]:
print(t[1:,2:])

[[6]
 [9]]


In [36]:
print(t[[0,1,2],[0,1,1]])

[1 5 8]


In [38]:
r = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(r)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [44]:
row = np.array([[0,1],[1,1]])
cols = np.array([[1,2],[1,0]])
print(r[row,cols])

[[1 5]
 [4 3]]


In [47]:
print(r[r>3])

[ 4  5  6  7  8  9 10 11]


In [48]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,2,3])
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [50]:
print(a+b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [54]:
y = np.arange(0,60,5)
y = y.reshape(3,4)
print(y)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [56]:
for x in np.nditer(y):
    print(x+5)

5
10
15
20
25
30
35
40
45
50
55
60
